# Generated by Django 2.2.4 on 2019-11-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantRegisteModel',
            fields=[
                ('merchantid', models.AutoField(primary_key=True, serialize=False)),
                ('merchantname', models.CharField(max_length=30)),
                ('contactno', models.IntegerField(max_length=10, unique=True)),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
