# Generated by Django 2.2.4 on 2019-11-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantregistemodel',
            name='merchantid',
            field=models.IntegerField(default=False, primary_key=True, serialize=False),
        ),
    ]
