# Generated by Django 2.2.4 on 2019-11-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20191108_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProductModel',
            fields=[
                ('productid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
