# Generated by Django 2.2.4 on 2019-11-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_merchantproductmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantproductmodel',
            name='mid',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='adminapp.MerchantRegisteModel'),
        ),
    ]
